theme: jekyll-theme-minimal
title: HC
description: Bookmark this to keep an eye on my project updates!

plugins:
  - jekyll-sitemap

collections:
  clients:
    output: false
  topics:
    output: true
    permalink: /topics/:path/
  blog:
    output: true
    permalink: /blog/:path/
  services:
    output: true
    permalink: /:path/
  stories: 
    output: true
    permalink: /stories/:path/
