theme: jekyll-theme-minimal
title: HC
description: Bookmark this to keep an eye on my project updates!
paginate: 5


collections:
  blog:
    output: true
    permalink: /blog/:path/
  services:
    output: true
    permalink: /services/:path/
  stories: 
    output: true
    permalink: /stories/:path/
