theme: jekyll-theme-minimal
title: HC
description: Bookmark this to keep an eye on my project updates!

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  clients:
    output: false
  category:
    output: true
    permalink: /blog/category/:path/
  people:
    output: true
    permalink: /people/:path/
  blog:
    output: true
    permalink: /blog/:path/
  services:
    output: true
    permalink: /:path/
  mobile-app-development:
    output: true
    permalink: /mobile-app-development/:path/
  stories: 
    output: true
    permalink: /stories/:path/
